# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

#remote_theme: "mmistakes/jekyll-theme-basically-basic"

# Site Settings
lang: en-US
title: Serkan Kuşcan
email: serkankuscan@yandex.com
description: "Your new default Jekyll theme"
baseurl: # the optional subpath of your site, e.g. "/blog"
# baseurl: "/jekyll-theme-basically-basic"
url: http://localhost:4000 # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
#repository: "mmistakes/minimal-mistakes"
author:
  name: Serkan Kuşcan
  twitter: serkankuscan
  picture: /assets/images/serkan.jpg
twitter_username: serkankuscan
github_username: serkankuscan
logo: /assets/icons/serkan.svg # path of site logo, e.g. "/assets/images/logo.png"
google_analytics: UA-114370836-1
disqus:
  shortname: serkankuscan-github-io
search: true
search_full_content: true
search_provider: lunr
algolia:
  application_id: ATRZ056E2Z
  index_name: serkankuscan.github.io
  search_only_api_key: 2560fee310e4ba548c6e3fab9a3cc543
  powered_by: true

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
#permalink: /:categories/:title/
#timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  #- jekyll-remote-theme

# Jekyll Feed
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  extjs:
    output: true
    permalink: /:collection/:path/
  veritabanidersleri:
    output: true
    permalink: /:collection/:path/	
  javase:
    output: true
    permalink: /:collection/:path/	

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _veritabanidersleri
  - scope:
      path: "_veritabanidersleri"
      type: veritabanidersleri
    values:
      layout: post
      read_time: true
  # _extjs
  - scope:
      path: "_extjs"
      type: extjs
    values:
      layout: post
      read_time: true	  
  # _java
  - scope:
      path: "_javase"
      type: javase
    values:
      layout: post
      read_time: true	  
